# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Defaults": "00_config.ipynb"}

modules = ["config.py"]

doc_url = "https://PhilBrockman.github.io"/"  #ModelAssistedLabel/"

git_url = "https://github.com/PhilBrockman/ModelAssistedLabel/tree/master/"

def custom_doc_links(name): return None
