# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Defaults": "00_ultralytics.ipynb",
         "prepare_YOLOv5": "00_ultralytics.ipynb",
         "FileUtilities": "01_split.ipynb",
         "Generation": "01_split.ipynb",
         "Trainer": "02_train.ipynb",
         "prepare_split": "index.ipynb",
         "organize": "index.ipynb",
         "generate_weights": "index.ipynb",
         "tidy_weights": "index.ipynb"}

modules = ["core.py",
           "examples.py"]

doc_url = "https://PhilBrockman.github.io/ModelAssistedLabel/"

git_url = "https://github.com/PhilBrockman/ModelAssistedLabel/tree/master/"

def custom_doc_links(name): return None
