repository: PhilBrockman/ModelAssistedLabel
output: web
topnav_title: Model-assisted Labeling with YOLOv5
site_title: Model-assisted Labeling with YOLOv5
company_name: Phil Brockman
description: A description of your project
# Set to false to disable KaTeX math
use_math: true
# Add Google analytics id if you have one and want to use it here
google_analytics:
# See http://nbdev.fast.ai/search for help with adding Search
google_search:

host: 127.0.0.1
# the preview server used. Leave as is.
port: 4000
# the port where the preview is rendered.

exclude:
  - .idea/
  - .gitignore
  - vendor
 
exclude: [vendor]

highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

sidebars:
- home_sidebar

plugins:
    - jekyll-remote-theme
    
remote_theme: fastai/nbdev-jekyll-theme
<<<<<<< HEAD
baseurl: /#ModelAssistedLabel/
theme: jekyll-theme-slate
=======
baseurl: /#ModelAssistedLabel/
theme: jekyll-theme-midnight
>>>>>>> 42483d941c5966e74f9d63351b3f19da75aa31a1
